# Generated by Django 4.0.3 on 2022-03-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='added_at',
            new_name='created_at',
        ),
    ]
